apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    tier: persistance
  annotations:
  namespace: components
spec:
  selector:
    matchLabels:
      node: ri
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        tier: persistance
        octopusexport: OctopusExport
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          args:
            - '--bind_ip'
            - 0.0.0.0
          ports:
            - name: mongo-port
              containerPort: 27017
              protocol: TCP
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
