apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion
  labels:
    app: api
    tier: rest
  namespace: components
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: api
        tier: rest
        octopusexport: OctopusExport
    spec:
      containers:
      - image: tmforumorg/promotion-management_tmf-671:4.0.0
        imagePullPolicy: IfNotPresent
        name: service-ordering
        ports:
        - containerPort: 8080
          name: ordering
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: tmforumorg-dh
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30