apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-partyapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-partyapi
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-partyapi
        version: reference-partyapi-latest
    spec:
      containers:
      - name: {{.Release.Name}}-partyapi
        image: localhost:5000/tmf632_api-party_v4.0.0:batch
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}           
        imagePullPolicy: Always
        ports:
        - name: {{.Release.Name}}-partyapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/party/v4/individual
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5          
          failureThreshold: 30 
         
